# Generated by Django 4.0 on 2022-01-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=50, verbose_name='Razão Social')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Pregao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('pregao', models.CharField(max_length=50, verbose_name='Licitação')),
                ('ata', models.CharField(max_length=50, verbose_name='Ata de Extrato Parcial')),
                ('resumo', models.TextField(max_length=500, verbose_name='Resumo')),
                ('objeto', models.TextField(max_length=500, verbose_name='Objeto da Licitação')),
                ('dom', models.CharField(max_length=50, verbose_name='DOM')),
                ('realinhamento', models.CharField(blank=True, max_length=50, verbose_name='Realinhamento')),
                ('retificacao', models.CharField(blank=True, max_length=50, verbose_name='Retificação')),
                ('homologacao', models.DateField(verbose_name='Homolocação')),
                ('prazo', models.CharField(max_length=50, verbose_name='Prazo de Entrega')),
            ],
            options={
                'verbose_name': 'Pregão',
                'verbose_name_plural': 'Pregões',
            },
        ),
        migrations.CreateModel(
            name='Pregoeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('rg', models.CharField(max_length=20, unique=True, verbose_name='RG')),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Pregoeiro',
                'verbose_name_plural': 'Pregoeiros',
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('comple_name', models.CharField(max_length=100, verbose_name='Solteiro e Brasileiro?')),
                ('rg', models.CharField(max_length=20, unique=True, verbose_name='RG')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
            },
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=50, verbose_name='Secretário')),
                ('rg', models.CharField(max_length=20, unique=True, verbose_name='RG')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Secretário',
                'verbose_name_plural': 'Secretarios',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('sigla', models.CharField(max_length=50, verbose_name='Sigla')),
                ('nome_secretaria', models.CharField(max_length=100, verbose_name='Secretaria')),
                ('nome_fundo', models.CharField(max_length=100, verbose_name='Fundo')),
                ('secretario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.secretario', verbose_name='Secretario')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('n_contrato', models.CharField(max_length=15, unique=True, verbose_name='Número do Contrato')),
                ('n_pedido', models.CharField(max_length=15, unique=True, verbose_name='Número do Pedido')),
                ('n_processo', models.CharField(max_length=15, unique=True, verbose_name='Número do Processo')),
                ('dt_protocolo', models.DateField(verbose_name='Data do Protocolo')),
                ('n_liberacao', models.CharField(max_length=15, unique=True, verbose_name='Liberação')),
                ('dt_liberaca', models.CharField(max_length=50, verbose_name='Data da Liberação')),
                ('empenho', models.CharField(choices=[('ordinario', 'Ordinário'), ('global', 'Global')], max_length=10, verbose_name='Empenho')),
                ('vigencia', models.CharField(max_length=50, verbose_name='Vigência')),
                ('proj_atividade', models.CharField(max_length=50, verbose_name='Projeto Atividade')),
                ('elemento_despesa', models.CharField(max_length=50, verbose_name='Elemento de Despesa')),
                ('fonte_recurso', models.CharField(max_length=50, verbose_name='Fonte de Recurso')),
                ('cod_aplicacao', models.CharField(max_length=50, verbose_name='Código de Aplicação')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('objeto', models.TextField(max_length=500, verbose_name='Objeto da Processo')),
                ('justificativa', models.TextField(max_length=500, verbose_name='Justificativa do Processo')),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('pregao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregao', verbose_name='Pregão')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.secretaria', verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.AddField(
            model_name='pregao',
            name='pregoeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregoeiro', verbose_name='Pregoeiro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.representante', verbose_name='Representante'),
        ),
    ]
