# Generated by Django 4.0 on 2022-01-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_processo_n_liberacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='n_liberacao',
            field=models.CharField(max_length=15, unique=True, verbose_name='Número do Liberação'),
        ),
    ]
